name: url_shortener
description: Flutter take-home â€“ URL shortener
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '^3.9.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  injectable: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
