dependencies:
  get_it: ^7.7.0
  injectable: ^2.4.2
  flutter_bloc: ^8.1.6
  http: ^1.2.2

dev_dependencies:
  mocktail: ^1.0.4
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1
  flutter_test:
    sdk: flutter
